[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding_platform = "ARsfrJ4ZYVKHsnvNM3GU4HtRsV9Nru9XiXgDAEMYJaxm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/cihan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
